[package]
name = "mrpack-downloader"
version = "0.1.1"
edition = "2021"
description = "Downloader for ModRinth modpacks (.mrpack files)"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async_zip = { version = "0.0.11", features = ["full"] }
reqwest = { version = "0.11", features = ["stream"] }
tokio = { version = "1.24", features = ["full"] }
clap = { version = "4.1", features = ["derive"] }
indicatif = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
semver = { version = "1.0", features = ["serde"] }
url = { version = "2.2", features = ["serde"] }
futures-util = "0.3"
