name: deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            os_suffix: linux
            extension: ""
          - os: windows-latest
            os_suffix: win.exe
            extension: .exe
          - os: macos-latest
            os_suffix: macos
            extension: ""
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
    - name: Build
      uses: actions-rs/cargo@v1.0.1
      with:
        command: build
        args: --release
    - name: Generate hashes
      shell: bash
      run: |
        cp target/release/mrpack-downloader${{ matrix.extension }} target/release/mrpack-downloader-${{ matrix.os_suffix }}
        sha256sum target/release/mrpack-downloader${{ matrix.extension }} > mrpack-downloader-${{ matrix.os_suffix }}.sha256
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/release/mrpack-downloader-${{ matrix.os_suffix }}
          mrpack-downloader-${{ matrix.os_suffix }}.sha256
